name: infra-studies

services:
  postgres:
    image: postgres:18-alpine
    container_name: infra-studies-postgres
    restart: on-failure:5
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./sql/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - "default"

  redis:
    image: redis:8-alpine
    container_name: infra-studies-redis
    restart: on-failure:5
    env_file:
      - ./.env
    command:
      - /bin/sh
      - -c
      - >-
        exec redis-server --appendonly yes
        --user "$${REDIS_USER}" on ">$${REDIS_PASSWORD}" "~*" "&*" "+@all"
        --user default off
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --user \"$${REDIS_USER}\" --pass \"$${REDIS_PASSWORD}\" ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - "default"

  customers.api:
    image: infra-studies/customers-api:latest
    container_name: infra-studies-customers-api
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: src/IS.Customers.API/Dockerfile
    ports:
      - 5000:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure:3
    networks:
      - "default"

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    driver: bridge